apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: quay.io/pires/docker-kibana:4.4.2
        env:
        - name: KIBANA_ES_URL
          value: "http://elasticsearch.default.svc.cluster.local:9200"
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: KIBANA_VERSION
          value: "4.4.2-linux-x64"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        volumeMounts:
        - name: kibana-config
          mountPath: /opt/kibana-4.4.2-linux-x64/config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
