apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  type: NodePort
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 5601
    nodePort: 30901
    protocol: TCP
